version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'store-db'
      MYSQL_USER: 'store'
      MYSQL_PASSWORD: 'store@123'
      MYSQL_ROOT_PASSWORD: 'store@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - store-db:/var/lib/mysql

  api:
    container_name: api
    depends_on:
      - db
    build: ./back/Dockerfile
    environment:
      DB_HOST: 'db'
    ports:
      - '80:80'
    links:
      - db
      
  site:
    container_name: site
    depends_on:
      - api
    build: ./front/Dockerfile
    ports:
      - '80:80'

volumes:
  store-db: